### ISSUE TITLE
Support for BTE API

### ISSUE THREAD

**Issue by StoneMcYT** [ASEAN-Build-The-Earth/Merlion#26]
**Is your feature request related to a problem? Please describe.**

No ability to check ur bte stats (Builder count, builds site count etc) via a bot

**Describe the solution you'd like**
Bot access BTE api and gets the data

**Describe alternatives you've considered**
Could have a bot access website and send the data manualy?

**Additional context**
NIL

**Comment by StoneMcYT** [comment]
Just need to add this here to remind myself

**Comment by StoneMcYT** [comment]
https://masteringjs.io/tutorials/axios/headers

For future use for axios api stuff

**Comment by tintinkung** [comment]
woa

**Comment by StoneMcYT** [comment]
Just need to format it then its done

**Comment by tintinkung** [comment]
`update:` sapphire framework does have command with this now

**Comment by tintinkung** [comment]
`update:` we now use our own api
