### ISSUE TITLE
v13 Embeds and message issue

### ISSUE THREAD

**Issue by tintinkung** [ASEAN-Build-The-Earth/Merlion#33]
upgrading to discord.js v13 have some issue with old code

i tried fix one command, heres how it should be
old | new(how it should be)
-------------|-----------------
![notfix](https://user-images.githubusercontent.com/77855014/136996917-d20881db-5fa5-43af-b9a7-7358f0f6cd1d.png) | ![fix](https://user-images.githubusercontent.com/77855014/136996933-927b253b-d845-4f6f-9f59-ba0c8ddd4845.png)

theres still many commands to fix ex. [help.js](https://github.com/ASEAN-Build-The-Earth/Merlion/blob/main/commands/System/help.js)
https://github.com/ASEAN-Build-The-Earth/Merlion/blob/3974b3b838c7c461d5846dca7d5e0e36d28a5526/commands/System/help.js#L17

will be so good if yall help fix these

**Comment by CommanderAstern** [comment]
I would like to work on this! @tintinkung

**Comment by tintinkung** [comment]
# ✔️ 90% Fixed
