### ISSUE TITLE
Discord buttons 

### ISSUE THREAD

**Issue by StoneMcYT** [ASEAN-Build-The-Earth/Merlion#60]
**Is your feature request related to a problem? Please describe.**
Frustrated that we keep using carlbot for reaction roles and links etc

**Describe the solution you'd like**
Using the discords buttons to well allow multiple things such as external URL sending reaction roles and more
![image](https://user-images.githubusercontent.com/67421882/137614967-4b83f874-3dae-42ba-8406-87cf27fdf38a.png)

**Describe alternatives you've considered**
NIL
**Additional context**
NIL

**Comment by StoneMcYT** [comment]
Placing this here so we can close it when this is added

**Comment by S4ge-Rites** [comment]
I would like to work on this please.

**Comment by StoneMcYT** [comment]
> I would like to work on this please.

Do you even how to use these?

**Comment by S4ge-Rites** [comment]
I understand what it does. It basically is an embed that has pages you can cycle through. I am looking at a tutorial at how to do it.

**Comment by S4ge-Rites** [comment]
what do you mean? im saying that like the buttons are on the embed and can link lets say like instead of one big embed that goes all the way down, you have pages you can cycle through to read the actual embed. meaning that you create the embed and you put in the buttons to cycle through

**Comment by StoneMcYT** [comment]
> what do you mean? im saying that like the buttons are on the embed and can link lets say like instead of one big embed that goes all the way down, you have pages you can cycle through to read the actual embed. meaning that you create the embed and you put in the buttons to cycle through

That is not the mainfocus of it and cyceling though isnt even the point

**Comment by S4ge-Rites** [comment]
sorry about that then

**Comment by tintinkung** [comment]
stop all dat @S4ge-Rites can work on it first, if it come out work, it works

**Comment by StoneMcYT** [comment]
> stop all dat @S4ge-Rites can work on it first, if it come out work, it works

We need finish the old projects though

**Comment by tintinkung** [comment]
`update:` able to do with sapphire framework

**Comment by tintinkung** [comment]
`update:` later
