### ISSUE TITLE
Delete command once sent

### ISSUE THREAD

**Issue by StoneMcYT** [ASEAN-Build-The-Earth/Merlion#61]
**Is your feature request related to a problem? Please describe.**
Messy chat when the commands are left there

**Describe the solution you'd like**
If not already delete the command message and at the bottom of the command place like Requested by USERNAME#0000

**Comment by tintinkung** [comment]
`update:` able to do with sapphire framework

**Comment by tintinkung** [comment]
`update:` had this feature in some command
