### ISSUE TITLE
[Feature]: Image manipulation commands

### ISSUE THREAD

**Issue by Kira272921** [ASEAN-Build-The-Earth/Merlion#65]
### What is this command? 

Image manipulation commands transforms a image by using the avatar of the user

### How can you make this 

You can use `canvacord` to do this, they have lot of pre - made things related to image manipulation 

### Demo of this image manipulation command 
![image](https://user-images.githubusercontent.com/90365542/137854232-ca407a8f-f8fa-4567-86b9-7a22c66df1a6.png)
![image](https://user-images.githubusercontent.com/90365542/137854265-62e95acf-b378-4915-ac3b-ea4af3c472d0.png)
![image](https://user-images.githubusercontent.com/90365542/137854305-6e0dc9d4-69a1-4d02-8e3b-29142bcd0788.png)

**Comment by tintinkung** [comment]
seems cool imma try it some day

**Comment by Kira272921** [comment]
> > > Amazing idea by the way would be useful for fun commands just wondering is canvacord required or can we use canvas This is Canva's npm page https://www.npmjs.com/package/canvas
> > 
> > 
> > I guess we require canvacord 😕 I really don't know that much about js, i came across while i was searching for image manipulation tutorials for my bot which uses discord.py
> 
> Since our bot runs on JavaScript we may have to use canvas also its fine not knowing much since we all start as beginners at one point. Also some info on canvas by the Discord.js official guide https://discordjs.guide/popular-topics/canvas.html

Ahh i get it now 
By canvas you have to do some stuff which are already pre made in canvas cord, i guess it would be easier to use and work with canvas cord

**Comment by tintinkung** [comment]
`update:` later
